version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "API_URL=http://${GATEWAY_HOST}:${INTERNAL_PORT}"

  router:
    container_name: ${ROUTER_HOST}
    build: ./backend/router
    depends_on:
      - datadog-agent
    expose:
      - "${INTERNAL_PORT}"
    command: flask run --host 0.0.0.0 --port ${INTERNAL_PORT} --debug --no-reload
    volumes:
      - cache:${CACHE_DIR}
    environment:
      - "FLASK_APP=${FLASK_APP}"
      - "INTERNAL_PORT=${INTERNAL_PORT}"
      - "CACHE_DIR=${CACHE_DIR}"

  api-gateway:
    container_name: ${GATEWAY_HOST}
    build: ./backend/api-gateway
    depends_on:
      - router
      - datadog-agent
    ports:
      - "${INTERNAL_PORT}:${INTERNAL_PORT}"
    command: flask run --host 0.0.0.0 --port ${INTERNAL_PORT} --debug --no-reload
    environment:
      - "FLASK_APP=${FLASK_APP}"
      - "ROUTER_URI=${ROUTER_HOST}:${INTERNAL_PORT}"
      - "INTERNAL_PORT=${INTERNAL_PORT}"
      - "CORS_ORIGINS=${CORS_ORIGINS}"

  user-service:
    build: ./backend/user-service
    expose:
      - "${INTERNAL_PORT}"
    command: flask run --host 0.0.0.0 --port ${INTERNAL_PORT} --debug --no-reload
    depends_on:
      user-db:
        condition: service_healthy
      router:
        condition: service_started
      datadog-agent:
        condition: service_started
    environment:
      - "DB_URI=postgresql://${USER_DB_USERNAME}:${USER_DB_PASSWORD}@${USER_DB_HOST}:${INTERNAL_DB_PORT}/${USER_DB_NAME}"
      - "FLASK_APP=${FLASK_APP}"
      - "ROUTER_URI=${ROUTER_HOST}:${INTERNAL_PORT}"
      - "INTERNAL_PORT=${INTERNAL_PORT}"
      - "INIT_DATA=${USER_INIT_DATA}"

  authentication-service:
    build: ./backend/authentication-service
    expose:
      - "${INTERNAL_PORT}"
    command: flask run --host 0.0.0.0 --port ${INTERNAL_PORT} --debug --no-reload
    depends_on:
      authentication-db:
        condition: service_healthy
      router:
        condition: service_started
      datadog-agent:
        condition: service_started
    environment:
      - "DB_URI=postgresql://${AUTH_DB_USERNAME}:${AUTH_DB_PASSWORD}@${AUTH_DB_HOST}:${INTERNAL_DB_PORT}/${AUTH_DB_NAME}"
      - "FLASK_APP=${FLASK_APP}"
      - "ROUTER_URI=${ROUTER_HOST}:${INTERNAL_PORT}"
      - "INTERNAL_PORT=${INTERNAL_PORT}"
      - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
      - "INIT_DATA=${AUTH_INIT_DATA}"
      - "TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}"
      - "TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}"
      - "TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}"

  email-service:
    build: ./backend/email-service
    depends_on:
      router:
        condition: service_started
      datadog-agent:
        condition: service_started
    expose:
      - "${INTERNAL_PORT}"
    command: flask run --host 0.0.0.0 --port ${INTERNAL_PORT} --debug --no-reload
    environment:
      - "FLASK_APP=${FLASK_APP}"
      - "ROUTER_URI=${ROUTER_HOST}:${INTERNAL_PORT}"
      - "INTERNAL_PORT=${INTERNAL_PORT}"
      - "MAILGUN_API_BASE_URL=${MAILGUN_API_BASE_URL}"
      - "MAILGUN_API_KEY=${MAILGUN_API_KEY}"
      - "MAILGUN_DOMAIN_NAME=${MAILGUN_DOMAIN_NAME}"
      - "APP_BASE_URL=${APP_BASE_URL}"

  user-db:
    container_name: ${USER_DB_HOST}
    image: postgres:15-alpine
    ports:
      - "5436:${INTERNAL_DB_PORT}"
    volumes:
      - user-data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=${USER_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${USER_DB_PASSWORD}"
      - "POSTGRES_DB=${USER_DB_NAME}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

  authentication-db:
    container_name: ${AUTH_DB_HOST}
    image: postgres:15-alpine
    ports:
      - "5435:${INTERNAL_DB_PORT}"
    volumes:
      - authentication-data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=${AUTH_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}"
      - "POSTGRES_DB=${AUTH_DB_NAME}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

  datadog-agent:
    container_name: datadog-agent
    image: datadog/agent:7
    logging:
      driver: none
    ports:
      - "8126:8126"
    environment:
      - "DD_API_KEY=${DD_API_KEY}"
      - "DD_SITE=us5.datadoghq.com"
      - "DD_LOGS_ENABLED=true"
      #      - "DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true"
      - 'DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"'
      - "DD_TAGS=env:${ENV}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  user-data:
  authentication-data:
  cache: